# Generated by Django 5.2.16 on 2026-08-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_contactrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_by',
            field=models.CharField(default='Administrator', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.CharField(default='Administrator', max_length=150),
        ),
        migrations.AddField(
            model_name='supplier',
            name='created_by',
            field=models.CharField(default='Administrator', max_length=150),
        ),
    ]
