# Generated by Django 5.2.16 on 2026-08-08 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_category_created_by_product_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('destination', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('transfer', 'Inter-warehouse Transfer'), ('supplier_return', 'Return to Supplier')], default='transfer', max_length=50)),
                ('status', models.CharField(choices=[('dispatched', 'Dispatched'), ('returned_to_stock', 'Returned to Stock')], default='dispatched', max_length=50)),
                ('dispatched_by', models.CharField(default='Administrator', max_length=150)),
                ('approved_by', models.CharField(blank=True, max_length=150, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='inventory.product')),
            ],
        ),
    ]
