# Generated by Django 5.2.16 on 2026-08-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_branchtransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('admin_name', models.CharField(default='Administrator', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='branchtransfer',
            name='company_slug',
            field=models.CharField(db_index=True, default='default', max_length=150),
        ),
        migrations.AddField(
            model_name='category',
            name='company_slug',
            field=models.CharField(db_index=True, default='default', max_length=150),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='company_slug',
            field=models.CharField(db_index=True, default='default', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='company_slug',
            field=models.CharField(db_index=True, default='default', max_length=150),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='company_slug',
            field=models.CharField(db_index=True, default='default', max_length=150),
        ),
        migrations.AddField(
            model_name='supplier',
            name='company_slug',
            field=models.CharField(db_index=True, default='default', max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_slug',
            field=models.CharField(db_index=True, default='default', max_length=150),
        ),
    ]
