# Generated by Django 5.2.16 on 2026-08-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_companyworkspace_branchtransfer_company_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='balance',
        ),
        migrations.AddField(
            model_name='companyworkspace',
            name='admin_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='date',
            field=models.CharField(default='just now', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='branchtransfer',
            name='approved_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='branchtransfer',
            name='destination',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='branchtransfer',
            name='dispatched_by',
            field=models.CharField(default='Administrator', max_length=100),
        ),
        migrations.AlterField(
            model_name='branchtransfer',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='branchtransfer',
            name='status',
            field=models.CharField(choices=[('dispatched', 'Dispatched Out'), ('returned_to_stock', 'Approved & Restocked')], default='dispatched', max_length=30),
        ),
        migrations.AlterField(
            model_name='branchtransfer',
            name='type',
            field=models.CharField(choices=[('branch_out', 'Inter-Branch Dispatch'), ('supplier_return', 'Supplier Return')], default='branch_out', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='type',
            field=models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out')], max_length=5),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='user',
            field=models.CharField(default='Admin User', max_length=100),
        ),
    ]
